import * as React from "react";

// Styles & context
import "../styles/index.css";
import ThemeContextProvider from "../context/ThemeContextProvider";
import { styled } from "@mui/material/styles";

// Custom components
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import NavbarBusiness from "../components/NavbarBusiness";
import Home from "./Home";
import Login from "./Login";
import HomeBusiness from "./HomeBusiness";
// Components
import { CssBaseline } from "@mui/material";
import { BrowserRouter, Route, Routes } from "react-router-dom";

const StyledWrapper = styled(`div`)(({ theme }) => ({
  display: "flex",
  flexDirection: "column",
  minHeight: "100vh", // Makes footer sticks to the end of the page, with long and short views
}));

const App = () => {
  return (
    <ThemeContextProvider>
      <CssBaseline />
      <header>
        <title>Deliver.ar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </header>
      <BrowserRouter>
        <StyledWrapper>
          <NavbarBusiness />
          <Routes>
            <Route path="*" element={<Home />} />
            <Route path="/login" element={<Login />} />
            <Route path="/HomeBusiness" element={<HomeBusiness />} />
          </Routes>
          <Footer />
        </StyledWrapper>
      </BrowserRouter>
    </ThemeContextProvider>
  );
};

export default App;
